[project]
name = 'truthChain_mainnet'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.truthchain_v1]
path = 'contracts/truthchain_v1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.truthchain_v2]
path = 'contracts/truthchain_v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.truthchain_v3]
path = 'contracts/truthchain_v3.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
